### ISSUE TITLE
Is this the new main project?

### ISSUE THREAD

**Issue by ghost** [sillsdev/taglib-sharp#4]
Hello sillsdev,

i want to use a ID3-Tag library in one of my projects but the original (mono/taglib-sharp) seems to be inactive for a very long time. Is your project the lates one or do u have specific goals which aren't in the main project?

Thank you for some information.
Best regards

**Comment by JohnThomson** [comment]
Unfortunately I'm not sure there IS a version that is being actively developed still. We don't have plans for it other than fixing bugs that cause us problems. Our hope was that these would be pulled into mono/taglib-sharp. We haven't succeeded yet, but did get one response to our PR from a 'collaborator'.

**Comment by papeh** [comment]
https://github.com/mono/taglib-sharp has had activity since this thread, in the last two years. It is still the main project.
